spring.application.name=audit-listener


# Server configuration
server.port=8080

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/audit_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Jackson configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# Kafka configuration
kafka.bootstrap-servers=localhost:9092
kafka.topics.http-requests=http-audit
kafka.topics.audit-events=general-audit
kafka.consumer.group-id=audit-listener-group
kafka.consumer.transaction-id-prefix=audit-listener-tx-

# Logging configuration
logging.level.com.webbee.auditlistener=DEBUG
logging.level.org.springframework.kafka=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Management endpoints configuration
#management.endpoints.web.exposure.include=health,info,prometheus
#management.endpoint.health.show-details=always

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/audit-listener-changelog.yaml
